<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAarb64b\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAarb64b/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAarb64b.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerAarb64b\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerAarb64b\EccubeProdProjectContainer([
    'container.build_hash' => 'Aarb64b',
    'container.build_id' => '606c8df9',
    'container.build_time' => 1608559188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAarb64b');
